#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

function run () {
	local NAME=$1
	pushd "$ROOT/$NAME" > /dev/null
	go run .
	popd > /dev/null
}

run examples/hello-world
